### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by StefanOstwald** [wngh1187/RawNeXt#1]
Great work @wngh1187 !

Can you share under which license you publish the code?
Thank you

**Comment by wngh1187** [comment]
@StefanOstwald! Thank you very much for your interest in my research.
Unfortunately, I didn't fully understand your question. 
What exactly does license mean?
I referenced the DLA and DSP technique codes from the github address below.
https://github.com/allenai/elastic/tree/master/models

**Comment by StefanOstwald** [comment]
@wngh1187 I was asking under which license you publish your code, for example MIT. You can do this by adding a license.txt to your repo. 

Currently it is not further specified, so it can’t be used by others.

**Comment by wngh1187** [comment]
@StefanOstwald Thank you so much for your valuable comments.
I created a MIT license file.
Please check this.
